version: '3.4'

services:
  parcs.daemon:
    image: ${DOCKER_REGISTRY-}parcsdaemon
    build:
      context: .
      dockerfile: Parcs.Daemon/Dockerfile
    volumes:
      - type: volume
        source: parcs.storage
        target: /var/lib/storage

  parcs.hostapi:
    image: ${DOCKER_REGISTRY-}parcshostapi
    build:
      context: .
      dockerfile: Parcs.HostAPI/Dockerfile
    volumes:
      - type: volume
        source: parcs.storage
        target: /var/lib/storage
    environment:
      Daemons__PreconfiguredInstances__0__HostUrl: parcs.daemon
      Daemons__PreconfiguredInstances__0__Port: 1111
      Foo: bar

volumes:
  parcs.storage: