version: '3.4'

services:
  parcs.daemon:
    image: ${DOCKER_REGISTRY-}parcsdaemon
    build:
      context: .
      dockerfile: Parcs.Daemon/Dockerfile
    volumes:
      - type: volume
        source: parcs.storage
        target: /var/lib/storage
    networks:
      - parcsnet
    depends_on:
      - parcs.hostapi

  parcs.hostapi:
    image: ${DOCKER_REGISTRY-}parcshostapi
    build:
      context: .
      dockerfile: Parcs.Host/Dockerfile
    volumes:
      - type: volume
        source: parcs.storage
        target: /var/lib/storage
    networks:
      - parcsnet
    depends_on:
      - parcs.database

  parcs.database:
    image: postgres:latest
    restart: always
    volumes:
      - parcs.database:/var/lib/postgresql/data/
    networks:
      - parcsnet

volumes:
  parcs.database:
  parcs.storage:

networks:
  parcsnet:
    driver: bridge  