version: '3.4'

services:
  parcs.daemon:
    image: ${DOCKER_REGISTRY-}parcsdaemon
    build:
      context: .
      dockerfile: Parcs.Daemon/Dockerfile
    volumes:
      - type: volume
        source: parcs.storage
        target: /var/lib/storage
    networks:
      - parcsnet

  parcs.hostapi:
    image: ${DOCKER_REGISTRY-}parcshostapi
    build:
      context: .
      dockerfile: Parcs.Host/Dockerfile
    volumes:
      - type: volume
        source: parcs.storage
        target: /var/lib/storage
    networks:
      - parcsnet

volumes:
  parcs.storage:
  
networks:
  parcsnet: